### Offerlist normal
GET http://localhost:3000/api/offers/offersList?offset=4400&limit=100

### returnOfferId
GET http://localhost:3000/api/offers/returnOfferId/37305

### OfferKeys
GET http://localhost:3000/api/offers/offerKeys/2506423 

### Offerlist com loop p descobrir jogos impossíveis
GET http://localhost:3000/api/offers/offersList?ids=74797,78621,26374

###
POST http://localhost:3000/api/offers/createOffer
Content-Type: application/json

{
    "product": "",
    "wholesale_mode": "0",
    "seller_price": 15,
    "tier_one_seller_price": "",
    "tier_two_seller_price": "",
    "status": 1,
    "keys": 3,
    "is_preorder": false
}

### searchOfferById productId = 45746
GET http://localhost:3000/api/offers/search/3027619

### O productId é "inútil" para editar
PUT http://localhost:3000/api/offers/editOffer
Content-Type: application/json

{
    "productId": 2750786, 
    "offerId": 2818018,
    "menorPreco": 0.69,
    "wholesale_mode": 1,
    "wholesale_price_tier_one": 0.70,
    "wholesale_price_tier_two": 0.70
}